### ISSUE TITLE
Flatten directory structure

### ISSUE THREAD

**Issue by jjhelmus** [openradar/AMS-Short-Course-on-Open-Source-Radar-Software#12]
Since the line between notebook and slides is blurry with the use of IPython for slides would be it acceptable to move the content of both the notebooks and slides directories into the root directory.  I think numbering the content to indicate the order would also be helpful.  I'll be happy to volunteer to do both if everyone approves.

**Comment by scollis** [comment]
Cool, no worries here.. I am also going to create a $PATH/data dir as 
well.. I will be putting data in there but I will NOT submit a PR 
changing paths to ./data/blah.wt until you submit your PR

When I make thumbdrives I will populate data with the data so that 
everything can be done relative

On 9/10/15 2:45 PM, Jonathan J. Helmus wrote:

> Since the line between notebook and slides is blurry with the use of 
> IPython for slides would be it acceptable to move the content of both 
> the notebooks and slides directories into the root directory. I think 
> numbering the content to indicate the order would also be helpful. 
> I'll be happy to volunteer to do both if everyone approves.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/openradar/AMS-Short-Course-on-Open-Source-Radar-Software/issues/12.

## 

I ride for Parkinsons research http://www.events.org/sponsorship.aspx?id=51573

**Comment by scollis** [comment]
I have put one file in the new place and I will be doing a PR soon for the Gridding NB.. Once you have moved the other NBs I will then make some slight changes to the Birds NB to allow relative paths to data so people can run IPYNB from Thumbdrive

**Comment by jjhelmus** [comment]
Sounds good, I think it should be possible for folks to run everything from the flash drive and not need to copy over to their machines.  Might be a bit slower for some IO but I don't think it will cause issues.

**Comment by jjhelmus** [comment]
Moving and renaming complete in PR #20.  Paths in notebooks will now need to be fixed.  I'll work on mine shortly.
